apiVersion: v1
kind: ConfigMap
metadata:
  name: users-svc
data:
  DATABASE_NAME: users
  application.yaml: |-
    config:
      text: sample-papi
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      text: dev-environment
    ---
    spring:
      config:
        activate:
          on-profile: uat
    config:
      text: uat-environment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: courses-svc
data:
  DATABASE_NAME: courses
  application.yaml: |-
    config:
      text: sample-papi
