apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-users
data:
  COURSES_URL: k8s-courses:8002/course
  DATABASE_NAME: users
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-courses
data:
  USERS_URL: k8s-users:8001/user
  DATABASE_NAME: courses
