# Use root/example as user/password credentials
version: '3.1'

services:

  courses:
    image: jdlearner/courses
    container_name: courses-service
    depends_on:
      - pg
    ports:
      - 8002:8002
    env_file:
      - ./courses/.env
    networks:
      - microservices-aws
  users:
    image: jdlearner/users
    container_name: users-service
    depends_on:
      - mysql8
    env_file:
      - ./users/.env
    ports:
      - 8001:8001
    networks:
      - microservices-aws
  mysql8:
    image: mysql
    restart: always
    container_name: mysql8
    ports:
      - 3350:3306
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: customPassword
      MYSQL_DATABASE: users
    networks:
      - microservices-aws
  pg:
    image: postgres:14
    restart: always
    container_name: pg
    ports:
      - 5490:5432
    volumes:
      - data-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: customPass
      POSTGRES_DB: courses
    networks:
      - microservices-aws

volumes:
  data-pg:
  data-mysql: 

networks:
  microservices-aws: