spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI}
      client:
        registration:
          users-svc-client:
            provider: spring
            client-id: users-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USERS_SVC_URI}/authorized
            scope: write
            client-name: users-svc-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI}
