spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users-svc
          predicates:
            - Path=/api/usuarios/**
          filters:
            - RewritePath=/api/usuarios/(?<segment>.*), /${segment}
        - id: courses-service
          uri: lb://courses-svc
          predicates:
            - Path=/api/cursos/**
          filters:
            - RewritePath=/api/cursos/(?<segment>.*), /course/${segment}


